### ISSUE TITLE
Load from Content/EmbeddedResource

### ISSUE THREAD

**Issue by ibebbs** [xiejiang2014/Xiejiang.SKLottie.Samples#1]
Great job on this library! Worked with every animation I tried.

Ideally, I would like to package Lottie animations as Content or Embedded Resource types so that output directory isn't littered with asset files. Unfortunately, it looks like this control only supports loading from a file?

For example, in the XAML below, the image loads correctly but the Lottie file does not (both are embedded resources):

```
<Border BorderThickness="0,0,0,1">
    <Image Source="pack://application:,,,/Assets/image.jpg" />
</Border>

<Border BorderThickness="0,0,0,1">
    <wpf:LottieViewer x:Name="LottieViewer" LottieFile="pack://application:,,,/Assets/lottie.json" />
</Border>
```

Is this something you intend to support?

Thanks again,
Ian

**Comment by xiejiang2014** [comment]
Good idea! Why didn't I think of that, thanks for the reminder.

**Comment by xiejiang2014** [comment]
Added "Source" property

resource
<wpf:LottieViewer x:Name = "LottieViewer"
                    Source = "pack://application:,,,/Assets/LottieLogo1.json" />

resource or relative path file
<wpf:LottieViewer x:Name = "LottieViewer"
                    Source = "/Assets/LottieLogo1.json" />

absolute path file
<wpf:LottieViewer x:Name = "LottieViewer"
                    Source = "c:\LottieLogo1.json" />

**Comment by ibebbs** [comment]
Amazing! I'll give it a shot thanks.

**Comment by ibebbs** [comment]
Tested. Works great, thanks!
