### ISSUE TITLE
Xiejiang.SKLottie.Views.Wpf Open-Source? License?

### ISSUE THREAD

**Issue by ibebbs** [xiejiang2014/Xiejiang.SKLottie.Samples#2]
Is the 'Xiejiang.SKLottie.Views.Wpf' component open-source? I've not been able to find a repository for it. I would happily submit PR's rather than issues if the source is available.

Also, what is the license for this component? I'm assuming that as it's based on the community toolkit it'll share a similar license?

**Comment by xiejiang2014** [comment]
Xiejiang.SKLottie.* is not currently open source, but it is free. The code still needs some cleaning.


All the code in LottieLoader is from https://github.com/CommunityToolkit/Lottie-Windows, I just modified a few files and added the code files related to parsing lottie into a new project,
Details: https://github.com/xiejiang2014/Microsoft.Toolkit.Uwp.UI.Lottie
[So its License please see the original project.](https://github.com/CommunityToolkit/Lottie-Windows/blob/main/LICENSE.md)

**Comment by ibebbs** [comment]
Great new. As I say, happy to help with this project if you'd like a hand.
