### ISSUE TITLE
可以加入位图绘制吗

### ISSUE THREAD

**Issue by fangjianh** [xiejiang2014/Xiejiang.SKLottie.Samples#6]

**Comment by xiejiang2014** [comment]
能提供样本吗？

**Comment by xiejiang2014** [comment]
> No description provided.

能提供样本吗？

**Comment by fangjianh** [comment]
[installing.zip](https://github.com/xiejiang2014/Xiejiang.SKLottie.Samples/files/9034374/installing.zip)

**Comment by xiejiang2014** [comment]
lottie 有两种方式使用位图
1 直接将位图转成字符串内嵌到json中,当前已实现,
2 类似你提供的样本这样,放在json文件的外面,当前尚未实现.

所以你可以先尝试使用第一种方式

另外我看到此样本中使用了模糊特效,当前也是没有实现的,
(其实是实现了,但是cpu绘图时进行模糊效率太低,帧数惨不忍睹,而gpu绘图的版本还有些不稳定)
不过也可以变通一下得到相同的效果,即预先制作好模糊后的图片将其叠加在未模糊的图片上,然后使用遮罩(mask)控制需要显示模糊的位置.

尽量不要使用蒙版(matte)

**Comment by xiejiang2014** [comment]
已实现直接读取 zip,等有空跑个测试再发出来

![Snipaste_2022-07-04_23-34-14](https://user-images.githubusercontent.com/44390984/177185152-c5798b8b-f12f-4d0c-9209-325ca0759249.png)

**Comment by xiejiang2014** [comment]
done
